In [5]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

iris = load_iris()
X, y = iris.data, iris.target

In [7]:
Y = np.vstack([1 - y, y])
observed = np.dot(Y, X)
observed

array([[ -79.1,   22.2, -204.4,  -89.1],
       [ 955.6,  435.9,  768.2,  268.9]])

In [ ]:

X = X + (np.random.rand(X.shape[0],X.shape[1])/10)

X_new = SelectKBest(chi2, k=2).fit_transform(X, y)
X_new

Y = np.vstack([1 - y, y])
observed = np.dot(Y, X)
observed

In [53]:
X = np.array([[1, 0, 0, 0, 1],[1, 1, 0, 1, 1],[1, 0, 0, 0, 0],[0, 0, 0, 0, 0],[0, 0, 0, 0, 1],[1, 0, 0, 0, 1],[1, 0, 1, 1, 1],[0, 1, 1, 0, 0],[1, 0, 1, 1, 1],[1, 1, 1, 1, 0]])
y = np.array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1])

From stackoverflow: https://stackoverflow.com/questions/21281328/scikit-learn-%CF%87%C2%B2-chi-squared-statistic-and-corresponding-contingency-table

In [54]:
y

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1])

In [55]:
1 - y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0])

In [56]:
Y = np.vstack([1 - y, y])
Y

array([[0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 0, 1]])

In [57]:
observed = np.dot(Y, X)
observed

array([[3, 1, 1, 2, 2],
       [4, 2, 3, 2, 4]])

In [58]:
feature_count = X.sum(axis=0)
feature_count

array([7, 3, 4, 4, 6])

In [59]:
class_prob = Y.mean(axis=1)
class_prob

array([0.4, 0.6])

In [60]:
expected = np.dot(feature_count.reshape(-1, 1), class_prob.reshape(1, -1)).T
expected

array([[2.8, 1.2, 1.6, 1.6, 2.4],
       [4.2, 1.8, 2.4, 2.4, 3.6]])

From source code: https://github.com/scikit-learn/scikit-learn/blob/a24c8b46/sklearn/feature_selection/univariate_selection.py#L171

In [47]:
import sklearn
Y2 = sklearn.preprocessing.LabelBinarizer().fit_transform(y)
Y2

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])

In [48]:
Y2 = np.append(1 - Y2, Y2, axis=1)
Y2

array([[0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1]])

In [49]:
observed2 = sklearn.utils.extmath.safe_sparse_dot(Y2.T, X) 
observed2

array([[3, 1, 1, 2, 2],
       [4, 2, 3, 2, 4]])

In [50]:
feature_count2 = X.sum(axis=0).reshape(1, -1)
feature_count2

array([[7, 3, 4, 4, 6]])

In [51]:
class_prob2 = Y2.mean(axis=0).reshape(1, -1)
class_prob2

array([[0.4, 0.6]])

In [52]:
expected2 = np.dot(class_prob2.T, feature_count2)
expected2

array([[2.8, 1.2, 1.6, 1.6, 2.4],
       [4.2, 1.8, 2.4, 2.4, 3.6]])

In [91]:
observed = np.array([[3,1],[4,2]])
observed

array([[3, 1],
       [4, 2]])

In [92]:
expected = np.array([[2.8, 1.2], [4.2, 1.8]])
expected

array([[2.8, 1.2],
       [4.2, 1.8]])

In [93]:
from scipy.stats import chisquare
score, pval = chisquare(observed, expected)

In [94]:
score

array([0.02380952, 0.05555556])

In [95]:
pval

array([0.87737056, 0.81366372])

In [80]:
(((3-2.8)**2)/2.8) + (((1-1.2)**2)/1.2) + (((4-4.2)**2)/4.2) + (((2-1.8)**2)/1.8)

0.07936507936507937

In [107]:
(((3-2.8)**2)/2.8) + (((4-4.2)**2)/4.2)

0.02380952380952385

In [104]:
chisquare([16, 18, 16, 14, 12, 12], f_exp=[100/6, 100/6, 100/6, 100/6, 100/6, 100/6])

Power_divergenceResult(statistic=3.200000000000002, pvalue=0.6691829020332429)

In [105]:
chisquare([16, 18, 16, 14, 12, 12])

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)

16.666666666666668